import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import Parser from 'rss-parser';
import { GoogleGenAI } from "@google/genai";

async function startServer() {
  const app = express();
  const PORT = 3000;
  
  app.use(express.json());

  // Lazy-initialize Gemini AI Client
  const getAIClient = () => {
    if (!process.env.GEMINI_API_KEY) {
      throw new Error("GEMINI_API_KEY environment variable is not configured. Please add it in Settings > Secrets.");
    }
    return new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  };

  // AI Chat Endpoint with Search Grounding & High Thinking support
  app.post("/api/ai/chat", async (req, res) => {
    const { prompt, history, useSearch, thinking } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: "Missing prompt" });
    }

    try {
      const ai = getAIClient();
      let model = "gemini-3.5-flash";
      const config: any = {};

      if (thinking) {
        model = "gemini-3.1-pro-preview";
        config.thinkingConfig = {
          thinkingLevel: "HIGH"
        };
      }

      if (useSearch) {
        config.tools = [{ googleSearch: {} }];
      }

      // Convert conversation history if present
      let contents: any[] = [];
      if (history && Array.isArray(history)) {
        contents = history.map((h: any) => ({
          role: h.role === "user" ? "user" : "model",
          parts: [{ text: h.text }]
        }));
      }
      contents.push({ role: "user", parts: [{ text: prompt }] });

      const response = await ai.models.generateContent({
        model,
        contents,
        config,
      });

      const text = response.text || "";
      const chunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
      const sources = chunks ? chunks.map((c: any) => ({
        title: c.web?.title || "Web Source",
        uri: c.web?.uri || ""
      })).filter((s: any) => s.uri) : [];

      res.json({ text, sources });
    } catch (error: any) {
      console.error("AI Chat Error:", error);
      res.status(500).json({ error: error.message || "Failed to generate AI response" });
    }
  });

  // AI Image Generation Endpoint supporting Sizes & Aspect Ratios
  app.post("/api/ai/generate-image", async (req, res) => {
    const { prompt, aspectRatio, imageSize } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: "Missing prompt" });
    }

    try {
      const ai = getAIClient();
      const selectedRatio = aspectRatio || "1:1";
      const selectedSize = imageSize || "1K";

      const response = await ai.models.generateContent({
        model: 'gemini-3.1-flash-image',
        contents: {
          parts: [{ text: prompt }],
        },
        config: {
          imageConfig: {
            aspectRatio: selectedRatio,
            imageSize: selectedSize
          }
        }
      });

      let imageUrl = "";
      if (response.candidates?.[0]?.content?.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            const base64Data = part.inlineData.data;
            const mime = part.inlineData.mimeType || "image/png";
            imageUrl = `data:${mime};base64,${base64Data}`;
            break;
          }
        }
      }

      if (!imageUrl) {
        throw new Error("No image data was generated by the model. Please try a different prompt.");
      }

      res.json({ imageUrl });
    } catch (error: any) {
      console.error("AI Image Generation Error:", error);
      res.status(500).json({ error: error.message || "Failed to generate image" });
    }
  });

  // RSS Proxy Endpoint
  app.get("/api/rss", async (req, res) => {
    const feedUrl = req.query.url as string;
    if (!feedUrl) {
      return res.status(400).json({ error: "Missing feed URL" });
    }
    
    try {
      const parser = new Parser({
        customFields: {
          item: [
            ['media:content', 'mediaContent'],
            ['image', 'image'],
            ['enclosure', 'enclosure']
          ]
        }
      });
      const feed = await parser.parseURL(feedUrl);
      res.json(feed);
    } catch (error) {
      console.error("RSS Fetch Error:", error);
      res.status(500).json({ error: "Failed to fetch RSS feed" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*all', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
